api_login_check:
    path: /api/users/login

controllers:
    resource: ../../src/Controller/
    type: annotation

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
